### PR TITLE
Update URLs to work with django 1.9+

### PR DESCRIPTION
**Pull request by katomaso**

### CODE REVIEW

**Comment by katomaso** [comment]
I think it would be necessary to drop compatibility with django versions < 1.8

**Comment by gotlium** [comment]
Pls, send pull request only to `development` branch.
About Django < 1.8. I think you are right. But Django 1.4 is previous LTS. I know, this version is not supported at this time, but many companies and projects used this version now. After 2.4, we can drop support 1.4.

**Comment by gotlium** [comment]
thnx:)

**Comment by katomaso** [comment]
That was fast! Should it even be merged to master? I would have happily changed the PR to development branch. Because I think we broke backward compatibility with django 1.4 now...

**Pull request merged**
